-- Runs against the deployed Supabase schema. ALL fixtures are rolled back.
begin;
do $$
declare eid uuid;cid uuid;aid uuid;bid uuid;uid uuid:=gen_random_uuid();pid uuid;rid uuid;outcome jsonb;before_real jsonb;after_real jsonb;count_before bigint;tests jsonb:='[]';d text;ok boolean;page jsonb;
begin
 insert into public.encuestas(titulo,departamento,provincia,distrito,estado,fecha_inicio,fecha_fin) values('DEMO TEST TRANSACCIONAL','Huancavelica','Tayacaja','Quichuas','ACTIVA',now()-interval '1 day',now()+interval '1 day') returning id into eid;
 insert into public.centros_poblados(nombre,tipo,departamento,provincia,distrito) values('COMUNIDAD DEMO TRANSACCIONAL','COMUNIDAD','Huancavelica','Tayacaja','Quichuas') returning id into cid;
 insert into public.candidatos(encuesta_id,nombre_completo,cargo,organizacion_politica) values(eid,'CANDIDATO DEMO A','CARGO DEMO','ORGANIZACION DEMO') returning id into aid;
 insert into public.candidatos(encuesta_id,nombre_completo,cargo,organizacion_politica) values(eid,'CANDIDATO DEMO B','CARGO DEMO','ORGANIZACION DEMO') returning id into bid;
 outcome=public.registrar_participacion('00000001','  José  ','Quispe','Huamán',cid,eid,aid,'qa-ip','qa-device-a',gen_random_uuid(),'QA','1.0',true);
 assert outcome->>'ok'='true','TEST 1 new valid DNI';tests=tests||'"01 nuevo DNI permitido"';
 select id into pid from public.participantes where dni='00000001';
 assert (select nombre_normalizado='JOSE QUISPE HUAMAN' from public.participantes where id=pid),'Normalization';tests=tests||'"Normalización SQL de nombres"';
 outcome=public.registrar_participacion('00000001','Otro','Nombre','',cid,eid,aid,'qa-ip','qa-device-a',gen_random_uuid(),'QA','1.0',true);
 assert outcome->>'code'='DNI_DUPLICADO','TEST 2 duplicate';assert (select count(*)=1 from public.participantes where dni='00000001'),'No duplicate participant';tests=tests||'"02 DNI repetido rechazado sin revelar datos"';
 outcome=public.registrar_participacion('ABC00001','Nombre','Prueba','',cid,eid,aid,'qa-ip','qa-device-a',gen_random_uuid(),'QA','1.0',true);assert outcome->>'code'='DNI_INVALIDO','TEST 3 letters';tests=tests||'"03 letras en DNI rechazadas"';
 foreach d in array array['1234567','123456789'] loop outcome=public.registrar_participacion(d,'Nombre','Prueba','',cid,eid,aid,'qa-ip','qa-device-a',gen_random_uuid(),'QA','1.0',true);assert outcome->>'code'='DNI_INVALIDO','TEST 4 length';end loop;tests=tests||'"04 longitud de DNI validada en SQL"';
 outcome=public.registrar_participacion('00000002','Jose','Quispe','Huaman',cid,eid,bid,'qa-ip','qa-device-b',gen_random_uuid(),'QA','1.0',true);assert outcome->>'ok'='true','TEST 5 homonym allowed';assert (select requiere_revision and fraud_score>=25 from public.participantes where dni='00000002'),'Homonym flagged';assert exists(select 1 from public.fraud_events where tipo='NOMBRE_COINCIDENTE' and encuesta_id=eid),'Homonym event';tests=tests||'"05 mismo nombre con DNI distinto permitido y marcado"';
 begin insert into public.respuestas(encuesta_id,participante_id,candidato_id,centro_poblado_id) values(eid,pid,aid,cid);raise exception 'TEST 6 duplicate allowed';exception when unique_violation then null;end;tests=tests||'"06 constraint de respuesta duplicada"';
 outcome=public.registrar_participacion('00000003','Otra','Persona','',cid,eid,aid,'qa-ip','qa-device-c',gen_random_uuid(),'QA','1.0',true);assert outcome->>'ok'='true','TEST 8 shared IP';tests=tests||'"08 misma IP con personas diferentes permitida"';
 begin perform set_config('role','anon',true);perform dni from public.participantes;raise exception 'TEST 9 public read allowed';exception when insufficient_privilege then null;end;tests=tests||'"09 público no consulta participantes"';
 begin perform set_config('role','anon',true);perform id from public.respuestas;raise exception 'TEST 10 public answers allowed';exception when insufficient_privilege then null;end;tests=tests||'"10 público no consulta respuestas individuales"';
 perform set_config('role','anon',true);assert (select sum(cantidad_respuestas)=3 from public.get_resultados_publicos(eid)),'TEST 11 public aggregate';perform set_config('role','none',true);tests=tests||'"11 resultados agregados públicos permitidos"';
 begin perform set_config('role','authenticated',true);perform public.admin_dashboard();raise exception 'TEST 12 roleless allowed';exception when insufficient_privilege then null;end;tests=tests||'"12 autenticado sin rol denegado"';
 insert into auth.users(id,aud,role,email,email_confirmed_at,created_at,updated_at) values(uid,'authenticated','authenticated','qa-'||uid||'@example.invalid',now(),now(),now());
 insert into public.profiles(id,nombre,rol) values(uid,'ADMIN DEMO TRANSACCIONAL','ADMIN');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',uid,'role','authenticated')::text,true);
 perform set_config('role','authenticated',true);assert public.admin_dashboard()->>'participantes' is not null,'TEST 13 admin';
 page=public.admin_list('participantes',1,'',null,'','',null,null,eid);assert page->'rows'->0->>'dni' like '****%','Masked DNI';
 perform set_config('role','none',true);tests=tests||'"13 ADMIN autorizado y DNI enmascarado"';
 select id into rid from public.respuestas where participante_id=pid;select count(*) into count_before from public.audit_logs where entidad='respuestas';
 perform public.review_response(rid,'INVALIDADA','REGISTRO_DE_PRUEBA','Prueba en transacción rollback');
 assert (select count(*)>count_before from public.audit_logs where entidad='respuestas'),'TEST 14 audit';tests=tests||'"14 invalidación auditada"';
 assert (select sum(cantidad_respuestas)=2 from public.get_resultados_publicos(eid)),'TEST 15 recalc count';assert (select min(porcentaje)=50 and max(porcentaje)=50 from public.get_resultados_publicos(eid)),'TEST 15 recalc percents';tests=tests||'"15 recálculo automático a 50/50"';
 select jsonb_agg(to_jsonb(r) order by r.id) into before_real from public.respuestas r where encuesta_id=eid;
 perform public.save_simulation(eid,jsonb_build_array(jsonb_build_object('candidato_id',aid,'porcentaje',70),jsonb_build_object('candidato_id',bid,'porcentaje',30)),1500);
 assert (select porcentaje=70 and cantidad_simulada=1050 from public.resultado_simulacion where candidato_id=aid),'TEST 16 simulation';tests=tests||'"16 edición de simulación 70/30"';
 select jsonb_agg(to_jsonb(r) order by r.id) into after_real from public.respuestas r where encuesta_id=eid;assert before_real=after_real,'TEST 17 isolation';tests=tests||'"17 simulación no modifica respuestas"';
 assert (select min(porcentaje)=50 and max(porcentaje)=50 from public.get_resultados_publicos(eid)),'TEST 19 source';tests=tests||'"19 resultados públicos nunca leen simulación"';
 perform public.reset_simulation(eid);assert not exists(select 1 from public.resultado_simulacion where encuesta_id=eid),'Reset sim';select jsonb_agg(to_jsonb(r) order by r.id) into after_real from public.respuestas r where encuesta_id=eid;assert before_real=after_real,'TEST 18 reset isolation';tests=tests||'"18 restablecer simulación no cambia datos reales"';
 assert not has_function_privilege('anon','public.registrar_participacion(text,text,text,text,uuid,uuid,uuid,text,text,uuid,text,text,boolean)','EXECUTE'),'Anon RPC registration';
 assert not has_table_privilege('anon','public.fraud_events','SELECT') and not has_table_privilege('anon','public.audit_logs','SELECT') and not has_table_privilege('anon','public.resultado_simulacion','SELECT'),'TEST 20 sensitive';
 assert not exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and not c.relrowsecurity),'RLS all';tests=tests||'"20 RLS y grants protegen datos sensibles"';
 outcome=public.registrar_participacion('00000004','Datos','Prueba','',cid,eid,gen_random_uuid(),'qa-ip','qa-device',gen_random_uuid(),'QA','1.0',true);assert outcome->>'code'='CANDIDATO_INVALIDO','Candidate mismatch';assert not exists(select 1 from public.participantes where dni='00000004'),'Atomic no orphan';tests=tests||'"Registro inválido no deja participante huérfano"';
 for i in 1..12 loop ok=public.consume_attempt('qa-limit-ip','qa-limit-device');assert ok,'Rate too low';end loop;assert not public.consume_attempt('qa-limit-ip','qa-limit-device'),'Rate failed';tests=tests||'"Rate limit persistente y evento antifraude"';
 update public.profiles set rol='VISUALIZADOR' where id=uid;
 begin perform public.review_response(rid,'VALIDA','CORRECCION_ADMINISTRATIVA','No permitido');raise exception 'Viewer wrote';exception when insufficient_privilege then null;end;tests=tests||'"VISUALIZADOR no puede revisar respuestas"';
 update public.profiles set rol='SUPERVISOR' where id=uid;perform public.review_response(rid,'VALIDA','CORRECCION_ADMINISTRATIVA','Revisión de supervisor');tests=tests||'"SUPERVISOR puede revisar respuestas"';
 begin perform public.save_simulation(eid,jsonb_build_array(jsonb_build_object('candidato_id',aid,'porcentaje',70),jsonb_build_object('candidato_id',bid,'porcentaje',30)),1500);raise exception 'Supervisor simulation';exception when insufficient_privilege then null;end;tests=tests||'"SUPERVISOR no modifica simulación"';
 update public.configuracion set mostrar_resultados=false where id=1;assert not exists(select 1 from public.get_resultados_publicos(eid)),'Hidden results leak';tests=tests||'"Ocultar resultados se aplica en SQL"';
 perform set_config('qa.rural_results',tests::text,true);
end$$;
select current_setting('qa.rural_results')::jsonb as passed_tests;
rollback;
